#!/bin/bash -e

cat <<EOF >/etc/systemd/system/net-dhcp.socket
[Unit]
Description=Docker Socket for DHCP driver

[Socket]
ListenStream=/run/docker/plugins/net-dhcp.sock
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
WantedBy=sockets.target
EOF

cat << EOF > /etc/systemd/system/net-dhcp.service
[Unit]
Description=Docker DHCP driver
Documentation=
Wants=network-online.target
After=network-online.target net-dhcp.socket

[Service]
KillMode=process
KillSignal=SIGTERM
ExecStartPre=/usr/lib/net-dhcp/up.sh
ExecStart=/usr/lib/net-dhcp/net-dhcp
Restart=always
RestartSec=10
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload

systemctl enable net-dhcp.socket && \
    systemctl start net-dhcp.socket

systemctl enable net-dhcp.service && \
    systemctl start net-dhcp.service
